source 'https://rubygems.org'

gemspec
ruby '~> 3.0'
# gem 'activerecord', '~> 7', '>= 7', require: 'active_record'
gem 'bcrypt'
gem 'linkeddata', '~> 3.2.0'
gem 'metainspector', '~> 5-11-2'
gem 'parseconfig', '~>1.1.2'
gem 'pry'
gem 'rake', '~> 13.0'
gem 'rdf-raptor', '~> 3.1.0'
gem 'require_all'
gem 'rest-client', '~>2.1.0'
gem 'rspec', '~> 3.11.0'
gem 'rubocop', '~> 1.21'
gem 'ruby-debug-ide'
gem 'shotgun'
gem 'sinatra', '~> 2.2'
# gem 'sinatra-json'
# gem 'sinatra-activerecord', require: 'sinatra/activerecord'
gem 'swagger-blocks', '~> 3.0.0'
gem 'sinatra-cross_origin'
gem 'thin'
gem 'tux'
gem 'xml-simple', '~>1.1.8'
gem 'fsp_harvester', '~> 0.1.9'
gem 'debase'

group :test do
  gem 'capybara'
  gem 'rack-test'
  # gem 'database_cleaner', git: 'https://github.com/bmabey/database_cleaner.git'
end
